### ISSUE TITLE
[인프라] DB 초안 설계

### ISSUE THREAD

**Issue by osj3474** [WhyNotHere/whynot-here-api-server#1]
사용자 인증/인가 처리를 제외하고, DB 스키마 작성필요합니다.

**Comment by osj3474** [comment]
리뷰 내용 공유드립니다.

=> <a href="https://github.com/WhyNotHere/whynot-here-api-server/blob/main/docs/DB_schema_v0.1.md" target="_blank">바로보기</a>

**Comment by doljae** [comment]
고생하셨습니다 :)
