### ISSUE TITLE
[BE] 기본 스키마 기준 API 개발

### ISSUE THREAD

**Issue by osj3474** [WhyNotHere/whynot-here-api-server#2]
<a href="https://www.notion.so/API-551d85e0eb914f1b9752ddd2b9aa431f" target="_blank">현 API 명세서</a> 개발 필요

**Comment by doljae** [comment]
GOGO 하시죵~

**Comment by osj3474** [comment]
#33 을 끝으로 현 API 명세서 기반 개발 완료하였습니다.
(Post 14개, Job 2개, 그 외(Security, S3 등) 5개)

ps. 댓글관련 API 추가 및 개발된 코드 리팩토링 필요합니다.
