### ISSUE TITLE
[BE] Swagger 설정 적용

### ISSUE THREAD

**Issue by doljae** [WhyNotHere/whynot-here-api-server#22]
- springdoc-openapi를 이용한 Swagger 글로벌 설정 정리
- Controller 메서드에 사용할 Swagger Annotation 생성 관련 스크립트 준비

**Comment by doljae** [comment]
우선 글로벌 설정 코드가 정리되면 PR로 머지한 뒤에 API 개발이 1차적으로 마무리 되면 적절하게 Annotation 추가 작업 진행하겠습니다 :)

**Comment by osj3474** [comment]
넵 알겠습니다~~:)

**Comment by doljae** [comment]
슬슬 하면 좋을 떄가 되었군요!
