### ISSUE TITLE
[BE] 예외처리 방식 논의

### ISSUE THREAD

**Issue by osj3474** [WhyNotHere/whynot-here-api-server#7]
refactor/exception-logic 브랜치 하나 따서 리뷰 필요.

**Comment by osj3474** [comment]
@doljae 님~!

혹시 브랜치 따지 않고 <a href="https://github.com/osj3474/SpringTips/tree/main/response-ok-fail/src/main/java/me/sangjin/response">Exception 처리 코드 템플릿</a> 로 리뷰진행 해도 될까요~?

**Comment by doljae** [comment]
> @doljae 님~!
> 
> 혹시 브랜치 따지 않고 [Exception 처리 코드 템플릿](https://github.com/osj3474/SpringTips/tree/main/response-ok-fail/src/main/java/me/sangjin/response) 로 리뷰진행 해도 될까요~?

코멘트 내용이 잘 이해가 안가서... 따로 작업 전에 Exception 관련해서 논의를 해보고싶다는 걸로 이해하면 될까요?

**Comment by osj3474** [comment]
진행하면서 리팩토링 해나가는 중입니다~
현재 논의 중인 건들은 따로 이슈가 열려있으니 이 이슈는 종료하겠습니다~

- filter단 예외처리
